apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: openshift-storage
  namespace: openshift-storage
spec:
  cephVersion:
    image: ceph/ceph:v14.2.2-20190722 # TODO Update to image we decide on
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    port: 8444
  network:
    hostNetwork: true
  rbdMirroring:
    workers: 0
  annotations:
  resources:
    mgr:
      requests:
          cpu: "1"
          memory: "3Gi"
      limits:
        cpu: "1"
        memory: "3Gi"
    mon:
      requests:
          cpu: "3"
          memory: "2Gi"
      limits:
        cpu: "3"
        memory: "2Gi"
    osd:
      requests:
          cpu: "2"
          memory: "4Gi"
      limits:
        cpu: "2"
        memory: "6Gi"
  storage:
    useAllNodes: true
    useAllDevices: true

